portfolio_analytics:
  target: dev
  outputs:
    dev:
      dbname: portfolio_db
      host: postgres
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: "{{ env_var('POSTGRES_USER') }}"

